name: logger_flutter_console
description: Flutter extension for logger. Please go there for documentation.
version: 0.7.1+2
author: Patrik Pfaffenbauer <patrik.pfaffenbauer@p3-software.eu> & Simon Leier <simonleier@gmail.com>
homepage: https://github.com/saiive/logger_flutter

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  logger: "^0.7.0"
  sensors: ^0.4.0+1